waypoints:
  tent:
    x_m: 19
    y_m: 24
    yaw_rad: 3.64
  tire_1:
    x_m: 27.4
    y_m: 1.05
    yaw_rad: 3.24
  tire_2:
    x_m: 23.9
    y_m: -5.7
    yaw_rad: 3.73
  palette:
    x_m: 17.4
    y_m: -10
    yaw_rad: 2.99
  containers:
    x_m: 7.4
    y_m: -17.67
    yaw_rad: 1.25
  enter_ramp:
    x_m: 1.7
    y_m: -13.7
    yaw_rad: 1.7
  in_ramp:
    x_m: -1.6
    y_m: -0.12
    yaw_rad: 2.61
  in_ramp_pivot:
    x_m: -1
    y_m: 1.1
    yaw_rad: 4.44
  out_ramp:
    x_m: 5.4
    y_m: -14.89
    yaw_rad: -0.46
  stair_containers:
    x_m: 10.72
    y_m: -6.5
    yaw_rad: 1.57
  containers_building:
    x_m: 7.2
    y_m: -1.09
    yaw_rad: -0.27
  containers_back:
    x_m: 7.5
    y_m: -0.5
    yaw_rad: -1.62
  back_building:
    x_m: 12
    y_m: 3.5
    yaw_rad: -0.8
  tire_3:
    x_m: 18
    y_m: 9
    yaw_rad: -1.9
  tire_4:
    x_m: 24
    y_m: 6
    yaw_rad: -1.6
  final:
    x_m: 30.4
    y_m: 8
    yaw_rad: 0.5